import type {
  AuthSession,
  CatalogueItem,
  CostBreakdown,
  CostNode,
  Evidence,
  ImportPreview,
  Meta,
  ProjectDetail,
  ProjectSummary,
  Report,
  ValidationResult,
  UserRecord,
} from "@/lib/api"

const zeroBreakdown = {
  material: "0",
  process: "0",
  fastener: "0",
  tooling: "0",
  total: "0",
} satisfies CostBreakdown

export const projectSummaryFixture = {
  id: "project-test-2026",
  name: "Formula SAE-A 2026",
  season: 2026,
  vehicle_type: "electric",
  entry_number: "E17",
  status: "draft",
  rule_source_document_id: "source-local-addendum",
  rule_pack_version: "2026.1",
  rule_pack_sha256: "rule-pack-sha256",
  catalogue_release_id: "catalogue-release-26-r1",
  catalogue_revision: "26_R1",
  cost_model: "competition-universal-dollar",
  project_summary: "A test cost-management summary.",
  numbering_convention: "SYS-ASM-PART-REV",
  bulk_method_summary: "Representative bulk-manufacturing methods.",
  report_setup_confirmed: 0,
  report_setup_confirmation: null,
  is_historical: false,
  archived_at: null,
  version: 3,
  created_at: "2026-07-29T00:00:00.000Z",
  updated_at: "2026-07-30T00:00:00.000Z",
} satisfies ProjectSummary

export const adminUserFixture = {
  id: "user-admin",
  email: "admin@ucmotorsport.example",
  displayName: "Aroha Chen",
  role: "admin",
  status: "active",
  createdAt: "2026-07-01T00:00:00.000Z",
  updatedAt: "2026-07-30T00:00:00.000Z",
  version: 2,
} satisfies UserRecord

export const editorUserFixture = {
  id: "user-editor",
  email: "engineer@ucmotorsport.example",
  displayName: "Elliot Rangi",
  role: "editor",
  status: "active",
  createdAt: "2026-07-02T00:00:00.000Z",
  updatedAt: "2026-07-30T00:00:00.000Z",
  version: 1,
} satisfies UserRecord

export const authSessionFixture = {
  user: adminUserFixture,
  expiresAt: "2026-07-31T00:00:00.000Z",
  csrfToken: "csrf-token-for-tests",
  capabilities: {
    canManageUsers: true,
    canManageImports: true,
    canManageSources: true,
  },
} satisfies AuthSession

export const projectSetupConfirmationFixture = {
  id: "setup-confirmation-test",
  contentHash:
    "a0c4bba68d995295adc4ad0a3bde0a685e8db9a9f93cec1c3a0f1f2f48a9c23b",
  confirmedAt: "2026-07-30T00:10:00.000Z",
  confirmedBy: {
    id: adminUserFixture.id,
    displayName: adminUserFixture.displayName,
    email: adminUserFixture.email,
  },
  projectVersion: 3,
} satisfies NonNullable<ProjectSummary["report_setup_confirmation"]>

export const partNodeFixture = {
  id: "node-part-upright",
  project_id: projectSummaryFixture.id,
  parent_id: "node-assembly-front-corner",
  kind: "part",
  system_code: "SU",
  raw_hla: null,
  raw_subassembly: null,
  raw_part_number: null,
  reference_id: "UPRIGHT-FR",
  full_number: "SU-001-001-A",
  name: "Front-right upright",
  description: "Representative machined suspension upright.",
  revision: "A",
  procurement_type: "made",
  quantity: "1",
  internal_note: "",
  source_import_batch_id: null,
  source_import_row: null,
  sort_order: 0,
  version: 2,
  costLines: [],
  breakdown: zeroBreakdown,
  children: [],
} satisfies CostNode

export const assemblyNodeFixture = {
  id: "node-assembly-front-corner",
  project_id: projectSummaryFixture.id,
  parent_id: "node-system-suspension",
  kind: "assembly",
  system_code: "SU",
  raw_hla: null,
  raw_subassembly: null,
  raw_part_number: null,
  reference_id: "FRONT-CORNER",
  full_number: "SU-001",
  name: "Front corner assembly",
  description: "Representative front suspension corner.",
  revision: "A",
  procurement_type: "made",
  quantity: "2",
  internal_note: "",
  source_import_batch_id: null,
  source_import_row: null,
  sort_order: 0,
  version: 1,
  costLines: [],
  breakdown: zeroBreakdown,
  children: [partNodeFixture],
} satisfies CostNode

export const systemNodeFixture = {
  id: "node-system-suspension",
  project_id: projectSummaryFixture.id,
  parent_id: "node-vehicle",
  kind: "system",
  system_code: "SU",
  raw_hla: null,
  raw_subassembly: null,
  raw_part_number: null,
  reference_id: null,
  full_number: null,
  name: "Suspension",
  description: "Suspension system.",
  revision: null,
  procurement_type: "unknown",
  quantity: "1",
  internal_note: "",
  source_import_batch_id: null,
  source_import_row: null,
  sort_order: 0,
  version: 1,
  costLines: [],
  breakdown: zeroBreakdown,
  children: [assemblyNodeFixture],
} satisfies CostNode

export const vehicleNodeFixture = {
  id: "node-vehicle",
  project_id: projectSummaryFixture.id,
  parent_id: null,
  kind: "vehicle",
  system_code: null,
  raw_hla: null,
  raw_subassembly: null,
  raw_part_number: null,
  reference_id: null,
  full_number: null,
  name: "UCM 2026 vehicle",
  description: "Representative test vehicle.",
  revision: null,
  procurement_type: "unknown",
  quantity: "1",
  internal_note: "",
  source_import_batch_id: null,
  source_import_row: null,
  sort_order: 0,
  version: 1,
  costLines: [],
  breakdown: zeroBreakdown,
  children: [systemNodeFixture],
} satisfies CostNode

export const projectDetailFixture = {
  project: {
    ...projectSummaryFixture,
    focusSystems: ["SU"],
  },
  tree: vehicleNodeFixture,
  flatNodes: [
    vehicleNodeFixture,
    systemNodeFixture,
    assemblyNodeFixture,
    partNodeFixture,
  ],
  breakdown: zeroBreakdown,
} satisfies ProjectDetail

export const validationFixture = {
  projectId: projectSummaryFixture.id,
  checkedAt: "2026-07-30T00:00:00.000Z",
  blockers: 1,
  warnings: 1,
  notices: 0,
  readyForCompetitionReport: false,
  issues: [
    {
      id: "report-setup-unconfirmed:project",
      severity: "blocker",
      code: "report-setup-unconfirmed",
      title: "Project report setup has not been confirmed",
      detail: "Review and save the report summaries in Project setup.",
      nodeId: null,
      ruleReference: "Local Addendum S.3.4.1",
    },
    {
      id: `part-visual-missing:${partNodeFixture.id}`,
      severity: "warning",
      code: "part-visual-missing",
      title: `${partNodeFixture.name} has no report-visible drawing or image`,
      detail: "Attach enough visual detail for judges to verify the part.",
      nodeId: partNodeFixture.id,
      ruleReference: "Local Addendum S.3.12.3",
    },
  ],
} satisfies ValidationResult

export const metaFixture = {
  application: "UCM Costing",
  currency: {
    code: "UNIVERSAL_DOLLAR",
    label: "Universal $",
    isRealCurrency: false,
  },
  rulePack: {
    version: "2026.1",
    sha256: "rule-pack-sha256",
  },
  catalogue: {
    releaseId: "catalogue-release-26-r1",
    revision: "26_R1",
    sha256: "catalogue-sha256",
  },
  systems: [
    { code: "BR", name: "Brakes" },
    { code: "DR", name: "Drivetrain" },
    { code: "CH", name: "Chassis" },
    { code: "AD", name: "Aerodynamics" },
    { code: "EL", name: "Electrical" },
    { code: "MS", name: "Miscellaneous" },
    { code: "ST", name: "Steering" },
    { code: "SU", name: "Suspension" },
    { code: "WT", name: "Wheels and Tyres" },
  ],
  features: {
    legacyImports: true,
    supportingWorkbook: true,
    costAmendments: true,
    cair: true,
    submissionPackages: true,
  },
  sourceDocuments: [
    {
      id: "source-local-addendum",
      kind: "governing-rule",
      title: "2026 Local Addendum",
      version: "2026.1",
      sha256: "source-document-sha256",
      applicability: "Formula SAE-A 2026",
      originalUrl: "https://www.sme-a.org/rules",
      downloadUrl:
        "/api/source-documents/source-local-addendum/download",
    },
  ],
  guardrails: [
    "Universal dollars are not a real currency.",
    "Competition-ready reports require zero blockers.",
  ],
} satisfies Meta

export const catalogueItemFixture = {
  id: "catalogue-item-aluminium",
  kind: "material",
  catalogueId: "MAT-AL-6061",
  name: "Aluminium 6061-T6",
  category: "Metal",
  supplier: null,
  unit: "kg",
  unit2: null,
  rawFormula: null,
  sourceFormula: null,
  effectiveFormula: null,
  formulaCorrection: null,
  effectiveFormulaValidation: null,
  fixedCost: "5.25",
  coefficients: {},
  metadata: {},
  sourceSheet: "Materials",
  sourceRow: 42,
  origin: "official",
  provenance: "official",
  revision: 0,
  latestChange: null,
} satisfies CatalogueItem

export const evidenceFixture = {
  id: "evidence-upright-drawing",
  node_id: partNodeFixture.id,
  project_id: projectSummaryFixture.id,
  kind: "drawing",
  display_name: "upright-drawing.pdf",
  content_sha256: "evidence-sha256",
  mime_type: "application/pdf",
  visibility: "internal",
  report_caption: "Front-right upright drawing",
  version: 0,
  created_at: "2026-07-30T00:00:00.000Z",
  updated_at: "2026-07-30T00:00:00.000Z",
  viewUrl: "/api/evidence/evidence-upright-drawing/view",
  downloadUrl: "/api/evidence/evidence-upright-drawing/download",
} satisfies Evidence

export const importPreviewFixture = {
  id: "import-preview-test",
  projectId: projectSummaryFixture.id,
  sourceName: "test-bom.csv",
  sourceSha256: "import-source-sha256",
  status: "preview",
  version: 0,
  preview: {
    template: "legacy-master",
    encoding: "utf-8",
    readOnly: true,
    issues: [],
    rawRows: [
      {
        rowNumber: 2,
        cells: ["SU", "Front corner assembly", "Front-right upright"],
      },
    ],
    records: [
      {
        recordKind: "component",
        system: "SU",
        hla: "01",
        subassembly: "01",
        partNumber: "SU.01.01.001",
        sourceKey: "SU.01.01.001",
        assemblyName: null,
        componentName: "Front-right upright",
        quantityOnCar: 1,
        provenance: {
          rowNumber: 2,
          rawCells: [
            "SU",
            "Front corner assembly",
            "Front-right upright",
          ],
          namedCells: {},
        },
      },
    ],
    stats: {
      rows: 1,
      candidates: 1,
    },
  },
  createdAt: "2026-07-30T00:00:00.000Z",
  committedAt: null,
  cancelledAt: null,
  createdBy: {
    id: adminUserFixture.id,
    displayName: adminUserFixture.displayName,
    email: adminUserFixture.email,
  },
} satisfies ImportPreview

export const reportFixture = {
  id: "report-draft-test",
  project_id: projectSummaryFixture.id,
  mode: "draft",
  status: "complete",
  pdf_sha256: "report-pdf-sha256",
  pdf_bytes: 4096,
  page_count: 4,
  created_at: "2026-07-30T00:00:00.000Z",
  completed_at: "2026-07-30T00:00:01.000Z",
  error_message: null,
  downloadUrl: "/api/reports/report-draft-test/download",
  validation: validationFixture,
  sourceHashes: {
    rulePack: metaFixture.rulePack.sha256,
    catalogue: metaFixture.catalogue.sha256,
  },
} satisfies Report
